---
title: Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
name: git.io/Skb
description: Mundana is a free Jekyll theme for awesome people like you, Medium like.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: "/blog"
disqus: sergknyz-github-io-blog
email: wowthemesnet@gmail.com
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  serg:
    name: Serg
    site: https://vk.com/opensong
    avatar: "/assets/images/avatar4.jpg"
    bio: Администратор сообщества Open Song Ru
    email: fakemail@gmail.com
    twitter: https://twitter.com/OpenSongRu
  natale:
    name: Natale
    site: https://vk.com/id4804187
    avatar: "/assets/images/avatar3.jpg"
    bio: на том и аминь.
    email: fakemail@gmail.com
    twitter: https://vk.com/id4804187
  sal:
    name: Sal
    site: https://www.wowthemes.net
    avatar: "/assets/images/avatar1.jpg"
    bio: Привет я Sal, автор Mundana, темы сайта которую вы используете. Надеюсь вам
      нравиться!
    email: wowthemesnet@gmail.com
    twitter: https://twitter.com/wowthemesnet
  jane:
    name: Jane
    site: https://www.wowthemes.net
    avatar: "/assets/images/avatar2.jpg"
    bio: Блоггер, модница, люблю новые идеи и писать статьи за чашечкой утреннего
      кофе!
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
